version: '3.9'

services:

  # api:
  #   container_name: api
  #   build: ./api
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./api:/usr/src/app

  fastapi:
    container_name: fastapi
    build: ./fastapi
    ports:
      - 8000:8000
    volumes:
      - ./fastapi:/usr/src/app   
    env_file:
      - .env       
    depends_on:
      - db        

  db:
    container_name: db
    build: ./back-end/db
    ports:
      - 5432:5432
    env_file:
      - .env
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data

  dbt:
    container_name: dbt
    build: ./back-end/dbt
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:8080      
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./back-end/dbt:/usr/src/app/dbt

  flows:
    container_name: flows
    build: ./back-end/flows
    depends_on:
        - db
    env_file:
      - .env
    ports:
      - 8050:8050
    restart: on-failure
    volumes:
      - ./back-end/flows:/usr/src/app

  # front-end:
  #   container_name: web-app
  #   build: ./front-end
  #   volumes:
  #     - './front-end:/app'
  #     - './front-end/node_modules:/app/node_modules'
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true