version: '3.9'

services:

  fastapi:
    container_name: fastapi
    build: ./fastapi
    ports:
      - 8000:8000
    volumes:
      - ./fastapi:/usr/src/app   
    env_file:
      - .env       
    depends_on:
      - db        

  db:
    container_name: db
    build: ./back-end/db
    ports:
      - 5432:5432
    env_file:
      - .env

  dbt:
    container_name: dbt
    build: ./back-end/dbt
    env_file:
      - .env
    ports:
      - 8080:8080      
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./back-end/dbt:/usr/src/app/dbt

  flows:
    container_name: flows
    build: ./back-end/flows
    env_file:
      - .env
    ports:
      - 8050:8050
    restart: on-failure
    volumes:
      - ./back-end/flows:/usr/src/app