import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// bar chart
import { MyResponsiveBar } from "../components/barChart";
import chartData from "../data/chartData.json";

// get data from api
export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const [offenseRes, neighborhoodRes, crimesRes] = await Promise.all([
    fetch("http://localhost:8000/offenses"),
    fetch("http://localhost:8000/neighborhoods"),
    fetch("http://localhost:8000/crimes"),
  ]);

  const [offenses, neighborhoods, crimes] = await Promise.all([
    offenseRes.json(),
    neighborhoodRes.json(),
    crimesRes.json(),
  ]);

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return { props: { offenses, neighborhoods } };
}

export default function Home(props) {
  console.log("here are the neighborhoods");
  console.log(JSON.stringify(props.neighborhoods));
  console.log("here are the offenses");
  console.log(JSON.stringify(props.offenses));
  return (
    <div className={styles.container}>
      <Head>
        <title>Crime!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Crime!</h1>
        <div className={styles.divchart}>
          <MyResponsiveBar data={chartData}></MyResponsiveBar>
          <p>Charts are above</p>
        </div>
      </main>
    </div>
  );
}
