// export async function getAllNeighborhoods() {
//   const res = await fetch('http://localhost:8000/neighborhoods');
//   const neighborhoods = await res.json();

//   return neighborhoods.map((neighborhood) => {
//     return {
//       params: {
//         id: neighborhood.neighborhood
//       }
//     };
//   });
// }

export function getAllNeighborhoods() {
  return [
    { params: { id: 'adair park' } },
    { params: { id: 'adams park' } },
    { params: { id: 'adamsville' } },
    { params: { id: 'almond park' } },
    { params: { id: 'amal heights' } },
    { params: { id: 'ansley park' } },
    { params: { id: 'arden/habersham' } },
    { params: { id: 'ardmore' } },
    { params: { id: 'argonne forest' } },
    { params: { id: 'arlington estates' } },
    { params: { id: 'ashley courts' } },
    { params: { id: 'ashview heights' } },
    { params: { id: 'atkins park' } },
    { params: { id: 'atlanta industrial park' } },
    { params: { id: 'atlanta university center' } },
    { params: { id: 'atlantic station' } },
    { params: { id: 'audubon forest' } },
    { params: { id: 'audubon forest west' } },
    { params: { id: 'baker hills' } },
    { params: { id: 'bakers ferry' } },
    { params: { id: 'bankhead' } },
    { params: { id: 'bankhead/bolton' } },
    { params: { id: 'bankhead courts' } },
    { params: { id: 'beecher hills' } },
    { params: { id: 'ben hill' } },
    { params: { id: 'ben hill acres' } },
    { params: { id: 'ben hill forest' } },
    { params: { id: 'ben hill pines' } },
    { params: { id: 'ben hill terrace' } },
    { params: { id: 'benteen park' } },
    { params: { id: 'berkeley park' } },
    { params: { id: 'betmar lavilla' } },
    { params: { id: 'blair villa/poole creek' } },
    { params: { id: 'blandtown' } },
    { params: { id: 'bolton' } },
    { params: { id: 'bolton hills' } },
    { params: { id: 'boulder park' } },
    { params: { id: 'boulevard heights' } },
    { params: { id: 'brandon' } },
    { params: { id: 'brentwood' } },
    { params: { id: 'briar glen' } },
    { params: { id: 'brookhaven' } },
    { params: { id: 'brookview heights' } },
    { params: { id: 'brookwood' } },
    { params: { id: 'brookwood hills' } },
    { params: { id: 'browns mill park' } },
    { params: { id: 'buckhead forest' } },
    { params: { id: 'buckhead heights' } },
    { params: { id: 'buckhead village' } },
    { params: { id: 'bush mountain' } },
    { params: { id: 'butner/tell' } },
    { params: { id: 'cabbagetown' } },
    { params: { id: 'campbellton road' } },
    { params: { id: 'candler park' } },
    { params: { id: 'capitol gateway' } },
    { params: { id: 'capitol view' } },
    { params: { id: 'capitol view manor' } },
    { params: { id: 'carey park' } },
    { params: { id: 'carroll heights' } },
    { params: { id: 'carver hills' } },
    { params: { id: 'cascade avenue/road' } },
    { params: { id: 'cascade green' } },
    { params: { id: 'cascade heights' } },
    { params: { id: 'castleberry hill' } },
    { params: { id: 'castlewood' } },
    { params: { id: 'center hill' } },
    { params: { id: 'chalet woods' } },
    { params: { id: 'channing valley' } },
    { params: { id: 'chastain park' } },
    { params: { id: 'chattahoochee' } },
    { params: { id: 'chosewood park' } },
    { params: { id: 'collier heights' } },
    { params: { id: 'collier hills' } },
    { params: { id: 'collier hills north' } },
    { params: { id: 'colonial homes' } },
    { params: { id: 'cross creek' } },
    { params: { id: 'custer/mcdonough/guice' } },
    { params: { id: 'deerwood' } },
    { params: { id: 'dixie hills' } },
    { params: { id: 'downtown' } },
    { params: { id: 'druid hills' } },
    { params: { id: 'east ardley road' } },
    { params: { id: 'east atlanta' } },
    { params: { id: 'east chastain park' } },
    { params: { id: 'east lake' } },
    { params: { id: 'edgewood' } },
    { params: { id: 'elmco estates' } },
    { params: { id: 'englewood manor' } },
    { params: { id: 'english avenue' } },
    { params: { id: 'english park' } },
    { params: { id: 'fairburn' } },
    { params: { id: 'fairburn heights' } },
    { params: { id: 'fairburn mays' } },
    { params: { id: 'fairburn road/wisteria lane' } },
    { params: { id: 'fairburn tell' } },
    { params: { id: 'fairway acres' } },
    { params: { id: 'fernleaf' } },
    { params: { id: 'florida heights' } },
    { params: { id: 'fort mcpherson' } },
    { params: { id: 'fort valley' } },
    { params: { id: 'garden hills' } },
    { params: { id: 'georgia tech' } },
    { params: { id: 'glenrose heights' } },
    { params: { id: 'grant park' } },
    { params: { id: 'green acres valley' } },
    { params: { id: 'greenbriar' } },
    { params: { id: 'greenbriar village' } },
    { params: { id: 'green forest acres' } },
    { params: { id: 'grove park' } },
    { params: { id: 'hammond park' } },
    { params: { id: 'hanover west' } },
    { params: { id: 'harland terrace' } },
    { params: { id: 'harris chiles' } },
    { params: { id: 'harvel homes community' } },
    { params: { id: 'heritage valley' } },
    { params: { id: 'high point' } },
    { params: { id: 'hills park' } },
    { params: { id: 'home park' } },
    { params: { id: 'horseshoe community' } },
    { params: { id: 'hunter hills' } },
    { params: { id: 'huntington' } },
    { params: { id: 'inman park' } },
    { params: { id: 'ivan hill' } },
    { params: { id: 'joyland' } },
    { params: { id: 'just us' } },
    { params: { id: 'kings forest' } },
    { params: { id: 'kingswood' } },
    { params: { id: 'kirkwood' } },
    { params: { id: 'knight park/howell station' } },
    { params: { id: 'lake claire' } },
    { params: { id: 'lake estates' } },
    { params: { id: 'lakewood' } },
    { params: { id: 'lakewood heights' } },
    { params: { id: 'laurens valley' } },
    { params: { id: 'leila valley' } },
    { params: { id: 'lenox' } },
    { params: { id: 'lincoln homes' } },
    { params: { id: 'lindbergh/morosgo' } },
    { params: { id: 'lindridge/martin manor' } },
    { params: { id: 'loring heights' } },
    { params: { id: 'magnum manor' } },
    { params: { id: 'margaret mitchell' } },
    { params: { id: 'marietta street artery' } },
    { params: { id: 'mays' } },
    { params: { id: 'meadowbrook forest' } },
    { params: { id: 'mechanicsville' } },
    { params: { id: 'mellwood' } },
    { params: { id: 'memorial park' } },
    { params: { id: 'midtown' } },
    { params: { id: 'midwest cascade' } },
    { params: { id: 'monroe heights' } },
    { params: { id: 'morningside/lenox park' } },
    { params: { id: 'mozley park' } },
    { params: { id: 'mt. gilead woods' } },
    { params: { id: 'mt. paran/northside' } },
    { params: { id: 'mt. paran parkway' } },
    { params: { id: 'niskey cove' } },
    { params: { id: 'niskey lake' } },
    { params: { id: 'none' } },
    { params: { id: 'north buckhead' } },
    { params: { id: 'norwood manor' } },
    { params: { id: 'oakcliff' } },
    { params: { id: 'oakland' } },
    { params: { id: 'oakland city' } },
    { params: { id: 'old fairburn village' } },
    { params: { id: 'old fourth ward' } },
    { params: { id: 'old gordon' } },
    { params: { id: 'orchard knob' } },
    { params: { id: 'ormewood park' } },
    { params: { id: 'paces' } },
    { params: { id: 'pamond park' } },
    { params: { id: 'peachtree battle alliance' } },
    { params: { id: 'peachtree heights east' } },
    { params: { id: 'peachtree heights west' } },
    { params: { id: 'peachtree hills' } },
    { params: { id: 'peachtree park' } },
    { params: { id: 'penelope neighbors' } },
    { params: { id: 'peoplestown' } },
    { params: { id: 'perkerson' } },
    { params: { id: 'peyton forest' } },
    { params: { id: 'piedmont heights' } },
    { params: { id: 'pine hills' } },
    { params: { id: 'pittsburgh' } },
    { params: { id: 'pleasant hill' } },
    { params: { id: 'polar rock' } },
    { params: { id: 'poncey-highland' } },
    { params: { id: 'princeton lakes' } },
    { params: { id: 'randall mill' } },
    { params: { id: 'rebel valley forest' } },
    { params: { id: 'regency trace' } },
    { params: { id: 'reynoldstown' } },
    { params: { id: 'ridgecrest forest' } },
    { params: { id: 'ridgedale park' } },
    { params: { id: 'ridgewood heights' } },
    { params: { id: 'riverside' } },
    { params: { id: 'rockdale' } },
    { params: { id: 'rosalie h. wright community council' } },
    { params: { id: 'rosedale heights' } },
    { params: { id: 'rue royal' } },
    { params: { id: 'sandlewood estates' } },
    { params: { id: 'scotts crossing' } },
    { params: { id: 'sherwood forest' } },
    { params: { id: 'south atlanta' } },
    { params: { id: 'south river gardens' } },
    { params: { id: 'south tuxedo park' } },
    { params: { id: 'southwest' } },
    { params: { id: 'springlake' } },
    { params: { id: 'state facility' } },
    { params: { id: 'summerhill' } },
    { params: { id: 'swallow circle/baywood' } },
    { params: { id: 'sweet auburn' } },
    { params: { id: 'sylvan hills' } },
    { params: { id: 'tampa park' } },
    { params: { id: 'the villages at carver' } },
    { params: { id: 'the villages at castleberry hill' } },
    { params: { id: 'the villages at east lake' } },
    { params: { id: 'thomasville heights' } },
    { params: { id: 'tuxedo park' } },
    { params: { id: 'underwood hills' } },
    { params: { id: 'venetian hills' } },
    { params: { id: 'vine city' } },
    { params: { id: 'virginia highland' } },
    { params: { id: 'washington park' } },
    { params: { id: 'wesley battle' } },
    { params: { id: 'west end' } },
    { params: { id: 'westhaven' } },
    { params: { id: 'west highlands' } },
    { params: { id: 'west lake' } },
    { params: { id: 'west manor' } },
    { params: { id: 'westminster/milar' } },
    { params: { id: 'westmont estates' } },
    { params: { id: 'westover plantation' } },
    { params: { id: 'west paces ferry/northside' } },
    { params: { id: 'westview' } },
    { params: { id: 'westwood terrace' } },
    { params: { id: 'whitewater creek' } },
    { params: { id: 'whittier mill village' } },
    { params: { id: 'wildwood forest' } },
    { params: { id: 'wildwood (npu-c)' } },
    { params: { id: 'wildwood (npu-h)' } },
    { params: { id: 'wilson mill meadows' } },
    { params: { id: 'wisteria gardens' } },
    { params: { id: 'woodfield' } },
    { params: { id: 'woodland hills' } },
    { params: { id: 'wyngate' } }
  ];
}
